Repository asterinas/vostd, pull requests merged in 2025-07, with the labels that each got.

#59 Rustc 1.88.0
  Cargo.lock
  rust-toolchain.toml
  vstd_extra/src/array_ptr.rs
  xtask/src/main.rs
Labels: enhancement

#70 Prove `admit()` related to va level
  lock-protocol/src/exec/rw/common.rs
  lock-protocol/src/exec/rw/cursor.rs
  lock-protocol/src/spec/utils.rs
Labels: AI-assist, pure proof

#72 `raw_ptr` in rw
  lock-protocol/src/exec/rw/cursor.rs
  lock-protocol/src/exec/rw/mem_content/meta_slot/mod.rs
  lock-protocol/src/exec/rw/node/mod.rs
  lock-protocol/src/mm/page_table/cursor/mod.rs
Labels: exec code

#96 Make build process more robust
  xtask/Cargo.lock
  xtask/src/main.rs
Labels: enhancement

#127 Provide fallback to powershell if pwsh is not present when bootstrapping
  xtask/src/main.rs
Labels: enhancement, good first issue

#158 Breaking: Update verus crate names
  Cargo.lock
  aster_common/Cargo.toml
  aster_common/src/cpu/set/atomic/spec.rs
  fvt13-vmspace-unmap-safety/src/spin/spec.rs
  fvt3-page-acquisition-safety/Cargo.toml
  fvt4-into-from-raw/Cargo.toml
  lock-protocol/src/exec/rcu/node/spinlock/mod.rs
  lock-protocol/src/exec/rw/node/rwlock/mod.rs
  lock-protocol/src/spec/rcu/atomic.rs
  lock-protocol/src/spec/rcu/tree.rs
  lock-protocol/src/spec/rcu/tree_refines_atomic.rs
  lock-protocol/src/spec/rw/atomic.rs
  lock-protocol/src/spec/rw/tree.rs
  lock-protocol/src/spec/rw/tree_refines_atomic.rs
  lock-protocol/src/spec/sub_pt/state_machine.rs
  lock-protocol/src/test/struct_test.rs
  lock-protocol/src/test/token_usage/common.rs
  lock-protocol/src/test/token_usage/exec_nid.rs
  lock-protocol/src/test/token_usage/mod.rs
  lock-protocol/src/test/token_usage/spin_lock.rs
  lock-protocol/src/test/tsm_test.rs
  vstd_extra/Cargo.toml
  xtask/src/main.rs
Labels: verification bug, inconsistency
